export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const SET_LOADING = "SET_LOADING";
export const GET_AUTH_USER = "GET_AUTH_USER";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT="LOGOUT";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const GET_LIST_PRODUITS="GET_LIST_PRODUITS";
export const GET_LIST_PRODUITS_SUCCES="GET_LIST_PRODUITS";
export const GET_LIST_PRODUITS_FAIL="GET_LIST_PRODUITS";

export const ADD_PRODUIT="ADD_PRODUIT";
export const ADD_PRODUIT_SUCCES="ADD_PRODUIT_SUCCES";
export const ADD_PRODUIT_FAIL="ADD_PRODUIT_FAIL";

export const GET_MY_LISTE_PRODUIT="GET_MY_LISTE_PRODUIT";
export const GET_MY_LISTE_PRODUIT_FAIL="GET_MY_LISTE_PRODUIT_FAIL";
export const GET_MY_LISTE_PRODUIT_SUCCES="GET_MY_LISTE_PRODUIT_SUCCES";

export const COMMANDER_PRODUIT_SUCCES ="COMMANDER_PRODUIT_SUCCES";
export const COMMANDER_PRODUIT_FAIL ="COMMANDER_PRODUIT_FAIL";

export const AFFICHER_PANIER ="AFFICHER_PANIER";
export const AFFICHER_PANIER_SUCCES ="AFFICHER_PANIER_SUCCES";
export const AFFICHER_PANIER_FAIL ="AFFICHER_PANIER_FAIL";

export const MODIFIER_PRODUIT ="MODIFIER_PRODUIT";
export const MODIFIER_PRODUIT_SUCCES ="MODIFIER_PRODUIT_SUCCES";
export const MODIFIER_PRODUIT_FAIL ="MODIFIER_PRODUIT_FAIL";

export const DELETE_PRODUIT ="DELETE_PRODUIT";
export const DELETE_PRODUIT_SUCCES ="DELETE_PRODUIT_SUCCES";
export const DELETE_PRODUIT_FAIL ="DELETE_PRODUIT_FAIL";

export const REFRESH_PANIER ="REFRESH_PANIER";
export const REFRESH_PANIER_SUCCES ="REFRESH_PANIER_SUCCES";
export const REFRESH_PANIER_FAIL ="REFRESH_PANIER_FAIL";

export const UPDATE_PROFIL ="UPDATE_PROFIL";
export const UPDATE_PROFIL_SUCCES ="UPDATE_PROFIL_SUCCES";
export const UPDATE_PROFIL_FAIL ="UPDATE_PROFIL_FAIL";

export const GET_ALL_USERS ="GET_ALL_USERS";
export const GET_ALL_USERS_SUCCES ="GET_ALL_USERS_SUCCES";
export const GET_ALL_USERS_FAIL ="GET_ALL_USERS_FAIL";

export const DELETE_USER ="DELETE_USER";
export const DELETE_USER_SUCCES ="DELETE_USER_SUCCES";
export const DELETE_USER_FAIL ="DELETE_USER_FAIL";